name: CMake and sanitizers

on: [push, pull_request]

jobs:
  ctestsanitizers:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1

    - name: Create build folder
      working-directory: homework/unique_ptr
      run: mkdir build
    - name: Compile
      working-directory: homework/unique_ptr/build
      run: |
        cmake ..
        make
    - name: Run tests
      working-directory: homework/unique_ptr/build
      run: ctest -V

    - name: Run sanitizers
      working-directory: homework/unique_ptr/build
      run: ./unique_ptr
